version: "3.7"

services:
  twego:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: twego
    tty: true
    volumes:
      - ./:/go/src/github.com/Fukkatsuso/twego
      - /root/.twego
